project_id = "iziunaqlgkfyasxoalwl"

[functions.sync-results]
verify_jwt = false

[functions.auto-close-matchdays]
verify_jwt = false

[functions.auto-sync-results]
verify_jwt = false
schedule = "*/1 * * * *"

[functions.fetch-fixtures]
verify_jwt = false

[functions.create-weekly-payment]
verify_jwt = false

[functions.verify-weekly-payment]
verify_jwt = false
